language: java
jdk:
- openjdk8
script: mvn clean verify


deploy:
  provider: heroku
  api_key:
    secure: JUM6je4LHNrTb8lner6G4poqchYlHMLxllkqD2GUDUr4XUslLDcLFZcxzOLckIwqBCVq0TGkV3TOMqByWf8bSPi8g7kyGXGUt7soL+1yeGRSaqixJVd90WBtfUFEIivjTAmCR5/Eb0rftfGJRWF14Zgb95+GhTN67xAtwBMbuQauPXGp38HkA/oGxPn/UWQ4/9KmMPC4vTYxwBN1IwZ31zcd7KN/lqhMRWiQx25hlxou5QFV38mmLM55qy+HUu5KdgOzeYlmvMT9XJYkPIQXbh9FM9LrQKUDHe1ZSELoETh1ixMjU4Le33V1Zr60HsKR0WXNOYr2Da+kImevYMbVmCoXxwVeOycCS63Ai+57yOz861/5z4DLjHiqacMVUIkaBsLw2xCeArNvzADUjrcdmsninMCz+fZjqKuxpwj3j94G8r/+cSIAQF1bxu1joF+Q5YZbtpiAXJo9f70g4PpgdNcmtwtUxDe8skeSfF4B3s7iyHIlVtelnYUvWPwwavX8vg7s3EUFnjuCBucJrBlPElV9kke8tgqjM4E3PYOffsntKq9um9qxm2MtNhuOYv3LdFkGL0YGO5JAiFjJxFIgHH1++i5EK8rUi5qLhmdVReq87Y5okRLAU69CERb/0tOUmYKdxQ8w8rDlM77C9kP+AO73GAOMACbIjzU68DK9MxA=
  app: rana-test-app
